### ISSUE TITLE
The license is unclear

### ISSUE THREAD

**Issue by detly** [zyedidia/json5#1]
(See also [issue #7](https://github.com/yosuke-furukawa/json5/issues/7) on the referenced project.)

There is no license or copyright information on this project, and it's not in the referenced project either. This is going to cause problems if you ever want to distribute, say, [micro](https://github.com/zyedidia/micro/) via distro package managers.

You might want to clarify or research the license, or switch to a dependency with clearer authorship/licensing.

**Comment by zyedidia** [comment]
Thanks for pointing this out. I found https://github.com/flynn/json5 which is pretty much a drop-in replacement and it provides a license. I have made the replacement in micro's code (see the referenced commit).

I suppose this repository is useless now but I'll still leave it around in case people are building old versions of micro from source.
